### ISSUE TITLE
Gateway Last Seen

### ISSUE THREAD

**Issue by seant100** [mycontroller-org/mycontroller#465]
The gateway last seen is never updated and after some time it says the gateway is "Down" with the red icon. All other sensor nodes are working.

**Comment by jkandasa** [comment]
@seant100 I have added a fix for this issue. You can check with [SNAPSHOT](https://forum.mycontroller.org/topic/58/download-snapshot-build) version.

When a gateway node(node Id: 0), goes down. Gateway will be reloaded. Status updated wrongly. I hope I have fixed this wrong status update.

**Comment by jkandasa** [comment]
@seant100 I tested this in my environment for the last 5 days. works well. If you see this issue in your environment kindly reopen this issue.

**Comment by seant100** [comment]
@jkandasa Sorry for the delay. I installed the latest snapshot today and checked 2 hours later and the Gateway node is down. So the problem is still there.
Also, you state you trigger a reload when the node goes down. I have rules setup that send me an email if a node goes down. So that method means I will still get Gateway is down emails.
Can you not assume a Gateway is working if any of its Nodes are working. Since all traffic essentially comes from the Gateway then you can set the "Last Seen" on the Gateway when ANY data is received from any node.
